version: "3.9"

services:
  backend:
    deploy:
      replicas: 3
    image: toms-backend:latest
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      REACT_FRONTEND_URL: http://frontend/
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    env_file:
      - .env
    restart: unless-stopped

  frontend:
    deploy:
      replicas: 1
    image: toms-frontend:latest
    ports:
      - target: 80
        published: 3001
        protocol: tcp
        mode: host
    restart: unless-stopped
    environment:
      - REACT_APP_WEBSOCKET_URL=http://backend/ws/
      - REACT_APP_BACKEND_URL=http://backend/api/v1

  db:
    deploy:
      replicas: 1
    image: postgres:17
    restart: unless-stopped
    ports:
      - "5432:5432"
    networks:
      - default
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATABASE: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  zookeeper:
    deploy:
      replicas: 1
    image: confluentinc/cp-zookeeper:7.5.0
    ports:
      - "2181:2181"
    networks:
      - default
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - zookeeper_data:/var/lib/zookeeper/data
    restart: unless-stopped

  kafka:
    deploy:
      replicas: 1
    image: confluentinc/cp-kafka:7.5.0
    ports:
      - target: 9092
        published: 9092
        protocol: tcp
        mode: host
    networks:
      - default
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://toms_kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - kafka_data:/var/lib/kafka/data
    restart: unless-stopped
    depends_on:
      - zookeeper

  redis:
    deploy:
      replicas: 1
    image: redis:7
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "-h", "localhost", "ping"]

networks:
  default:
    name: toms_default
    driver: overlay
volumes:
  postgres_data:
  zookeeper_data:
  kafka_data:
  redis_data: 
